live_config_reload = true

[[colors.indexed_colors]]
color = "0xf78c6c"
index = 16

[[colors.indexed_colors]]
color = "0xff5370"
index = 17

[[colors.indexed_colors]]
color = "0x303030"
index = 18

[[colors.indexed_colors]]
color = "0x353535"
index = 19

[[colors.indexed_colors]]
color = "0xb2ccd6"
index = 20

[[colors.indexed_colors]]
color = "0xeeffff"
index = 21

[colors.bright]
black = "0x4a4a4a"
red = "0xd6295a"
green = "0x77e660"
yellow = "0xffb700"
blue = "0x415ed1"
magenta = "0xd060e6"
cyan = "0x00ffff"
white = "0xffffff"

[colors.cursor]
cursor = "0xeeffff"
text = "0x212121"

[colors.normal]
black = "0x212121"
red = "0xd6295a"
green = "0x77e660"
yellow = "0xffb700"
blue = "0x415ed1"
magenta = "0xd060e6"
cyan = "0x00ffff"
white = "0xffffff"

[colors.primary]
background = "0x181a20"
foreground = "0xeeffff"

[env]
TERM = "alacritty"

[font]
size = 9

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "SemiBold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "SemiBold Italic"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraBold Italic"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window]
opacity = 0.85

[window.padding]
x = 25
y = 25
